# Generated by Django 5.1.5 on 2025-02-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_title', models.CharField(max_length=100)),
                ('my_desc', models.TextField()),
            ],
        ),
    ]
